// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMfESKV9a7xJrenDIaVH49b8uevQCwnP4',
    appId: '1:260556650892:web:61e7683f791211cd2dfea9',
    messagingSenderId: '260556650892',
    projectId: 'new-app-notes-app',
    authDomain: 'new-app-notes-app.firebaseapp.com',
    storageBucket: 'new-app-notes-app.appspot.com',
    measurementId: 'G-P98SETEBLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEXQ88TYEr5xU4uS5KVvBAx37N5azQd8I',
    appId: '1:260556650892:android:5a5f0f3060b83aee2dfea9',
    messagingSenderId: '260556650892',
    projectId: 'new-app-notes-app',
    storageBucket: 'new-app-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXP5Co_PsKVbI2YQ2cr4L7SVl4YWi53xQ',
    appId: '1:260556650892:ios:5ac0d77e65bf83e12dfea9',
    messagingSenderId: '260556650892',
    projectId: 'new-app-notes-app',
    storageBucket: 'new-app-notes-app.appspot.com',
    iosBundleId: 'com.Shade.myNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXP5Co_PsKVbI2YQ2cr4L7SVl4YWi53xQ',
    appId: '1:260556650892:ios:f5c86404c2a3811f2dfea9',
    messagingSenderId: '260556650892',
    projectId: 'new-app-notes-app',
    storageBucket: 'new-app-notes-app.appspot.com',
    iosBundleId: 'com.Shade.myNotesApp.RunnerTests',
  );
}
