// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEXQ88TYEr5xU4uS5KVvBAx37N5azQd8I',
    appId: '1:260556650892:android:a8bf00707a9197702dfea9',
    messagingSenderId: '260556650892',
    projectId: 'new-app-notes-app',
    storageBucket: 'new-app-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXP5Co_PsKVbI2YQ2cr4L7SVl4YWi53xQ',
    appId: '1:260556650892:ios:043d87246b03194d2dfea9',
    messagingSenderId: '260556650892',
    projectId: 'new-app-notes-app',
    storageBucket: 'new-app-notes-app.appspot.com',
    iosClientId:
        '260556650892-5hgr142o2jdv3v3p5460cpssjunbnkal.apps.googleusercontent.com',
    iosBundleId: 'com.Shade.my_notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXP5Co_PsKVbI2YQ2cr4L7SVl4YWi53xQ',
    appId: '1:260556650892:ios:043d87246b03194d2dfea9',
    messagingSenderId: '260556650892',
    projectId: 'new-app-notes-app',
    storageBucket: 'new-app-notes-app.appspot.com',
    iosClientId:
        '260556650892-5hgr142o2jdv3v3p5460cpssjunbnkal.apps.googleusercontent.com',
    iosBundleId: 'com.Shade.my_notes',
  );
}
